name: Typecho Post Auto Pulish 
on:
  push:
    branches:    
      - main
jobs:
  push:
      runs-on: ${{ matrix.operating-system }}
      strategy:
        matrix:
          # in this example, there is a newer version already installed, 3.7.7, so the older version will be downloaded
          operating-system: ['ubuntu-20.04']
      permissions:
        # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
        contents: write
      steps:
      - uses: actions/checkout@v3 # Checking out the repo
      - name: Run with setup-python 3.10
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.10'
          update-environment: false
          cache: 'pipenv'
      - name: Install pipenv
        run: pip3 install --user pipenv
      - name: Install dependecies
        run:  pipenv --python python3 && pipenv install
      - name: Build
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          XMLRPC_PHP: ${{ secrets.XMLRPC_PHP }}
        run: pipenv run build
      - name: GitHub Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with: 
          commit_message: Github Action Automated Updated
          file_pattern: '.md_sha1 README.md'
                
